name: hifi-wdl
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::miniwdl=1.13.*
  - conda-forge::singularity
  - conda-forge::miniwdl-slurm=0.4.*
  - bioconda::biopython
  - bioconda::samtools
